/** Output languages for the Learn tab: English name, native name, flag. */
export interface Lang {
  name: string
  native: string
  flag: string
}

export const AUTO: Lang = { name: 'Auto', native: 'same as question', flag: '🌐' }

export const LANGUAGES: Lang[] = [
  { name: 'English', native: 'English', flag: '🇬🇧' },
  { name: 'Burmese', native: 'မြန်မာ', flag: '🇲🇲' },
  { name: 'Thai', native: 'ไทย', flag: '🇹🇭' },
  { name: 'Chinese (Simplified)', native: '简体中文', flag: '🇨🇳' },
  { name: 'Chinese (Traditional)', native: '繁體中文', flag: '🇹🇼' },
  { name: 'Japanese', native: '日本語', flag: '🇯🇵' },
  { name: 'Korean', native: '한국어', flag: '🇰🇷' },
  { name: 'Vietnamese', native: 'Tiếng Việt', flag: '🇻🇳' },
  { name: 'Indonesian', native: 'Bahasa Indonesia', flag: '🇮🇩' },
  { name: 'Malay', native: 'Bahasa Melayu', flag: '🇲🇾' },
  { name: 'Filipino', native: 'Filipino', flag: '🇵🇭' },
  { name: 'Khmer', native: 'ខ្មែរ', flag: '🇰🇭' },
  { name: 'Lao', native: 'ລາວ', flag: '🇱🇦' },
  { name: 'Shan', native: 'တႆး', flag: '🇲🇲' },
  { name: 'Mon', native: 'ဘာသာမန်', flag: '🇲🇲' },
  { name: 'Karen (S\'gaw)', native: 'ကညီ', flag: '🇲🇲' },
  { name: 'Hindi', native: 'हिन्दी', flag: '🇮🇳' },
  { name: 'Bengali', native: 'বাংলা', flag: '🇧🇩' },
  { name: 'Urdu', native: 'اردو', flag: '🇵🇰' },
  { name: 'Punjabi', native: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  { name: 'Gujarati', native: 'ગુજરાતી', flag: '🇮🇳' },
  { name: 'Marathi', native: 'मराठी', flag: '🇮🇳' },
  { name: 'Tamil', native: 'தமிழ்', flag: '🇮🇳' },
  { name: 'Telugu', native: 'తెలుగు', flag: '🇮🇳' },
  { name: 'Kannada', native: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { name: 'Malayalam', native: 'മലയാളം', flag: '🇮🇳' },
  { name: 'Sinhala', native: 'සිංහල', flag: '🇱🇰' },
  { name: 'Nepali', native: 'नेपाली', flag: '🇳🇵' },
  { name: 'Tibetan', native: 'བོད་སྐད་', flag: '🏔️' },
  { name: 'Mongolian', native: 'Монгол', flag: '🇲🇳' },
  { name: 'Arabic', native: 'العربية', flag: '🇸🇦' },
  { name: 'Persian', native: 'فارسی', flag: '🇮🇷' },
  { name: 'Hebrew', native: 'עברית', flag: '🇮🇱' },
  { name: 'Turkish', native: 'Türkçe', flag: '🇹🇷' },
  { name: 'Kurdish', native: 'Kurdî', flag: '🏳️' },
  { name: 'Azerbaijani', native: 'Azərbaycan', flag: '🇦🇿' },
  { name: 'Kazakh', native: 'Қазақ', flag: '🇰🇿' },
  { name: 'Uzbek', native: 'Oʻzbek', flag: '🇺🇿' },
  { name: 'Georgian', native: 'ქართული', flag: '🇬🇪' },
  { name: 'Armenian', native: 'Հայերեն', flag: '🇦🇲' },
  { name: 'Russian', native: 'Русский', flag: '🇷🇺' },
  { name: 'Ukrainian', native: 'Українська', flag: '🇺🇦' },
  { name: 'Polish', native: 'Polski', flag: '🇵🇱' },
  { name: 'Czech', native: 'Čeština', flag: '🇨🇿' },
  { name: 'Slovak', native: 'Slovenčina', flag: '🇸🇰' },
  { name: 'Hungarian', native: 'Magyar', flag: '🇭🇺' },
  { name: 'Romanian', native: 'Română', flag: '🇷🇴' },
  { name: 'Bulgarian', native: 'Български', flag: '🇧🇬' },
  { name: 'Serbian', native: 'Српски', flag: '🇷🇸' },
  { name: 'Croatian', native: 'Hrvatski', flag: '🇭🇷' },
  { name: 'Bosnian', native: 'Bosanski', flag: '🇧🇦' },
  { name: 'Slovenian', native: 'Slovenščina', flag: '🇸🇮' },
  { name: 'Macedonian', native: 'Македонски', flag: '🇲🇰' },
  { name: 'Albanian', native: 'Shqip', flag: '🇦🇱' },
  { name: 'Greek', native: 'Ελληνικά', flag: '🇬🇷' },
  { name: 'Lithuanian', native: 'Lietuvių', flag: '🇱🇹' },
  { name: 'Latvian', native: 'Latviešu', flag: '🇱🇻' },
  { name: 'Estonian', native: 'Eesti', flag: '🇪🇪' },
  { name: 'Finnish', native: 'Suomi', flag: '🇫🇮' },
  { name: 'Swedish', native: 'Svenska', flag: '🇸🇪' },
  { name: 'Norwegian', native: 'Norsk', flag: '🇳🇴' },
  { name: 'Danish', native: 'Dansk', flag: '🇩🇰' },
  { name: 'Icelandic', native: 'Íslenska', flag: '🇮🇸' },
  { name: 'German', native: 'Deutsch', flag: '🇩🇪' },
  { name: 'Dutch', native: 'Nederlands', flag: '🇳🇱' },
  { name: 'French', native: 'Français', flag: '🇫🇷' },
  { name: 'Spanish', native: 'Español', flag: '🇪🇸' },
  { name: 'Catalan', native: 'Català', flag: '🏴' },
  { name: 'Portuguese (Brazil)', native: 'Português (Brasil)', flag: '🇧🇷' },
  { name: 'Portuguese (Portugal)', native: 'Português', flag: '🇵🇹' },
  { name: 'Italian', native: 'Italiano', flag: '🇮🇹' },
  { name: 'Irish', native: 'Gaeilge', flag: '🇮🇪' },
  { name: 'Welsh', native: 'Cymraeg', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
  { name: 'Swahili', native: 'Kiswahili', flag: '🇰🇪' },
  { name: 'Amharic', native: 'አማርኛ', flag: '🇪🇹' },
  { name: 'Hausa', native: 'Hausa', flag: '🇳🇬' },
  { name: 'Yoruba', native: 'Yorùbá', flag: '🇳🇬' },
  { name: 'Igbo', native: 'Igbo', flag: '🇳🇬' },
  { name: 'Zulu', native: 'isiZulu', flag: '🇿🇦' },
  { name: 'Xhosa', native: 'isiXhosa', flag: '🇿🇦' },
  { name: 'Afrikaans', native: 'Afrikaans', flag: '🇿🇦' },
  { name: 'Somali', native: 'Soomaali', flag: '🇸🇴' },
  { name: 'Malagasy', native: 'Malagasy', flag: '🇲🇬' },
  { name: 'Haitian Creole', native: 'Kreyòl ayisyen', flag: '🇭🇹' },
  { name: 'Esperanto', native: 'Esperanto', flag: '🏳️' },
  { name: 'Latin', native: 'Latina', flag: '🏛️' },
]
